apiVersion: v1
kind: Service
metadata:
  name: runner-backend
  labels:
    app: runner-backend
spec:
  type: {{ .Values.service.type }}
  selector:
    app: runner-backend
  ports:
    - name: http
      port: 80
      targetPort: {{ .Values.backend.port }}