apiVersion: apps/v1
kind: Deployment
metadata:
  name: runner-backend
  labels:
    app: runner-backend
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: runner-backend
  template:
    metadata:
      labels:
        app: runner-backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.backend.port }}
          readinessProbe:
            tcpSocket:
              port: {{ .Values.backend.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: {{ .Values.backend.port }}
            initialDelaySeconds: 15
            periodSeconds: 20