apiVersion: v1
kind: Service
metadata:
  name: {{ include "runner.fullname" . }}-backend
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "runner.labels" . | nindent 4 }}
    app: runner-backend
spec:
  selector:
    app: runner-backend
  ports:
  - port: {{ .Values.backend.service.port }}
    targetPort: {{ .Values.backend.service.targetPort }}
