apiVersion: apps/v1
kind: Deployment
metadata:
  name: runner-frontend
  labels:
    app: runner-frontend
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: runner-frontend
  template:
    metadata:
      labels:
        app: runner-frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.frontend.port }}
          readinessProbe:
            tcpSocket:
              port: {{ .Values.frontend.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: {{ .Values.frontend.port }}
            initialDelaySeconds: 15
            periodSeconds: 20