apiVersion: v1
kind: Service
metadata:
  name: runner-frontend
  labels:
    app: runner-frontend
spec:
  type: {{ .Values.service.type }}
  selector:
    app: runner-frontend
  ports:
    - name: http
      port: 80
      targetPort: {{ .Values.frontend.port }}