apiVersion: v1
kind: Service
metadata:
  name: {{ include "runner.fullname" . }}-frontend
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "runner.labels" . | nindent 4 }}
    app: runner-frontend
spec:
  selector:
    app: runner-frontend
  ports:
  - port: {{ .Values.frontend.service.port }}
    targetPort: 80
