{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: runner
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: "/$2"
spec:
  ingressClassName: {{ .Values.ingress.className | quote }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: {{ .Values.ingress.pathPrefixApi | quote }}   # e.g. /api(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: runner-backend
                port:
                  number: 80
          - path: {{ .Values.ingress.pathPrefixWeb | quote }}   # e.g. /
            pathType: Prefix
            backend:
              service:
                name: runner-frontend
                port:
                  number: 80
{{- end }}