{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: runner
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.className | quote }}
spec:
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: {{ .Values.ingress.pathPrefixApi }}
            pathType: Prefix
            backend:
              service:
                name: runner-backend
                port:
                  number: 80
          - path: {{ .Values.ingress.pathPrefixWeb }}
            pathType: Prefix
            backend:
              service:
                name: runner-frontend
                port:
                  number: 80
{{- end }}