apiVersion: v1
kind: Service
metadata:
  name: runner-frontend
spec:
  type: ClusterIP
  selector:
    app: runner-frontend
  ports:
    - port: 80
      targetPort: {{ .Values.frontend.port }}
      protocol: TCP