apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: runner-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/austinhogan11/Runner
    targetRevision: main
    path: deploy/helm/runner
    helm:
      valueFiles:
        - values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: runner
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
